# Generated by Django 5.0.3 on 2024-04-08 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('img', models.ImageField(upload_to='images/', verbose_name='картинка')),
                ('des', models.TextField(verbose_name='текст')),
                ('address', models.CharField(max_length=128, verbose_name='адресс')),
                ('price', models.CharField(max_length=32, verbose_name='цена')),
                ('max_human', models.IntegerField(verbose_name='макс. кол-во человек')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='юзер')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
            },
        ),
    ]
